name: Publish to NuGet

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  publish-fonibo-storage:
    name: Publish Fonibo.Storage
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        PROJECT_FILE_PATH: src/Fonibo.Storage/Fonibo.Storage.csproj
        INCLUDE_SYMBOLS: true
        
  publish-fonibo-storage-s3:
    name: Publish Fonibo.Storage.S3
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        PROJECT_FILE_PATH: src/Fonibo.Storage.S3/Fonibo.Storage.S3.csproj
        INCLUDE_SYMBOLS: true
